import os
import sys
import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import joblib

# Load .env
dotenv_path = os.path.join(os.path.dirname(__file__), "..", "backend", ".env")
if os.path.exists(dotenv_path):
    with open(dotenv_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                k, v = line.split('=', 1)
                os.environ[k.strip()] = v.strip()

# Ensure assets directory exists
os.makedirs("assets", exist_ok=True)

# ==========================================
# Database Connection Details
# ==========================================
db_user = os.getenv("DB_USER", "OMEGA_user")
db_pass = os.getenv("DB_PASSWORD", "omega123")
db_host = os.getenv("DB_HOST", "localhost")
db_port = os.getenv("DB_PORT", "1521")
db_name = os.getenv("DB_NAME", "orcl")

db_url = f"oracle+oracledb://{db_user}:{db_pass}@{db_host}:{db_port}/?service_name={db_name}"

print("=" * 60)
print("  OMEGA ML Model Training Script")
print("=" * 60)

def ensure_tables_exist_and_seeded(engine):
    with engine.connect() as conn:
        # Check and create crop_training_data
        try:
            conn.execute(text("SELECT 1 FROM crop_training_data WHERE ROWNUM = 1"))
        except Exception:
            print("  [INFO] Table 'crop_training_data' does not exist. Creating...")
            conn.execute(text("""
                CREATE TABLE crop_training_data (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    temperature NUMBER(10,2),
                    soil_type VARCHAR2(100),
                    crop VARCHAR2(100)
                )
            """))
            conn.commit()

        # Check and create fertilizer_training_data
        try:
            conn.execute(text("SELECT 1 FROM fertilizer_training_data WHERE ROWNUM = 1"))
        except Exception:
            print("  [INFO] Table 'fertilizer_training_data' does not exist. Creating...")
            conn.execute(text("""
                CREATE TABLE fertilizer_training_data (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    temperature NUMBER(10,2),
                    soil_type VARCHAR2(100),
                    predicted_crop VARCHAR2(100),
                    fertilizer VARCHAR2(100)
                )
            """))
            conn.commit()

        # Check and create ml_model_metadata
        try:
            conn.execute(text("SELECT 1 FROM ml_model_metadata WHERE ROWNUM = 1"))
        except Exception:
            print("  [INFO] Table 'ml_model_metadata' does not exist. Creating...")
            conn.execute(text("""
                CREATE TABLE ml_model_metadata (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    model_name VARCHAR2(100),
                    training_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    records_count NUMBER,
                    accuracy NUMBER(10,4),
                    status VARCHAR2(50)
                )
            """))
            conn.commit()

        # Now check if they are empty
        crop_count = conn.execute(text("SELECT COUNT(*) FROM crop_training_data")).scalar()
        fert_count = conn.execute(text("SELECT COUNT(*) FROM fertilizer_training_data")).scalar()

        if crop_count == 0 or fert_count == 0:
            print("  [INFO] Training tables are empty. Generating and seeding simulated data into Oracle DB...")
            np.random.seed(42)
            n_samples = 2000
            temperatures = np.round(np.random.uniform(8, 48, n_samples), 2)
            ALL_SOILS = [
                "Alkaline", "Alluvial", "Black", "Brown", "Chalky", "Chernozem", "Clayey", "Desert",
                "Forest", "Gravelly", "Laterite", "Lateritic", "Loamy", "Marshy", "Mediterranean",
                "Mountain", "Peaty", "Permafrost", "Podzol", "Red", "Saline", "Sandy", "Silty",
                "Tundra", "Volcanic", "Yellow"
            ]
            soils = np.random.choice(ALL_SOILS, n_samples)
            crops = []
            fertilizers = []

            ALL_CROPS = [
                "Almond", "Apple", "Arecanut", "Avocado", "Bamboo", "Banana", "Barley", "Barnyard Millet",
                "Beetroot", "Bitter Gourd", "Blackgram", "Bottle Gourd", "Brinjal", "Broccoli", "Cabbage",
                "Capsicum", "Carrot", "Cashew", "Cauliflower", "Chickpea", "Chili", "Cocoa", "Coconut",
                "Coffee", "Coriander", "Cotton", "Cowpea", "Cucumber", "Custard Apple", "Dragon Fruit",
                "Fig", "Finger Millet", "Flax", "Foxtail Millet", "Garlic", "Ginger", "Grapes", "Green Gram",
                "Groundnut", "Guava", "Horse Gram", "Jackfruit", "Jute", "Kidneybeans", "Kodo Millet",
                "Lentil", "Little Millet", "Lychee", "Maize", "Mango", "Millet", "Mint", "Mungbean",
                "Muskmelon", "Mustard", "Oats", "Onion", "Orange", "Papaya", "Peas", "Pearl Millet",
                "Pigeonpeas", "Pineapple", "Pomegranate", "Potato", "Pumpkin", "Quinoa", "Radish", "Rice",
                "Rubber", "Rye", "Saffron", "Sapota", "Sesame", "Sorghum", "Soybean", "Spinach", "Strawberry",
                "Sugarcane", "Sunflower", "Sweet Potato", "Tapioca", "Tea", "Tea Leaves", "Tobacco",
                "Tomato", "Turmeric", "Walnut", "Watermelon", "Wheat"
            ]

            for temp, soil in zip(temperatures, soils):
                if np.random.random() < 0.06:
                    crop = np.random.choice(ALL_CROPS)
                else:
                    if temp < 15:
                        if soil == "Loamy": crop = "Apple"
                        elif soil in ["Black", "Alluvial"]: crop = "Wheat"
                        elif soil in ["Sandy", "Laterite"]: crop = "Barley"
                        elif soil == "Red": crop = "Potato"
                        else: crop = "Chickpea"
                    elif 15 <= temp < 20:
                        if soil == "Loamy": crop = "Potato"
                        elif soil == "Black": crop = "Wheat"
                        elif soil in ["Alluvial", "Clayey"]: crop = "Barley"
                        elif soil in ["Sandy", "Laterite"]: crop = "Lentil"
                        else: crop = "Grapes"
                    elif 20 <= temp < 25:
                        if soil in ["Clayey", "Alluvial"]: crop = "Rice"
                        elif soil == "Loamy": crop = "Tomato"
                        elif soil == "Red": crop = "Pigeonpeas"
                        elif soil == "Black": crop = "Soybean"
                        elif soil == "Sandy": crop = "Onion"
                        else: crop = "Grapes"
                    elif 25 <= temp < 30:
                        if soil in ["Black", "Alluvial"]: crop = "Sugarcane"
                        elif soil == "Clayey": crop = "Rice"
                        elif soil == "Loamy": crop = "Banana"
                        elif soil == "Red": crop = "Mango"
                        elif soil == "Sandy": crop = "Groundnut"
                        else: crop = "Coffee"
                    elif 30 <= temp < 35:
                        if soil == "Black": crop = "Cotton"
                        elif soil == "Clayey": crop = "Jute"
                        elif soil == "Alluvial": crop = "Maize"
                        elif soil == "Loamy": crop = "Orange"
                        elif soil in ["Red", "Laterite"]: crop = "Papaya"
                        else: crop = "Watermelon"
                    else:
                        if soil in ["Black", "Alluvial", "Laterite"]: crop = "Cotton"
                        elif soil == "Sandy": crop = "Muskmelon"
                        else: crop = "Coconut"
                crops.append(crop)

                if crop in ["Apple", "Mango", "Banana", "Orange", "Papaya", "Grapes", "Pomegranate"]:
                    fert = "Vermicompost" if soil in ["Sandy", "Laterite", "Red"] else "Organic Compost"
                elif crop in ["Rice", "Wheat", "Maize", "Sugarcane", "Barley", "Jute"]:
                    fert = "Urea" if soil in ["Clayey", "Alluvial", "Loamy"] else "Ammonium Sulphate"
                elif crop in ["Cotton", "Soybean", "Groundnut", "Coconut", "Coffee"]:
                    fert = "DAP" if soil == "Black" else "MOP"
                else:
                    fert = "NPK 19-19-19" if soil in ["Sandy", "Loamy", "Red"] else "Superphosphate"
                fertilizers.append(fert)

            crop_params = [{"t": float(temperatures[i]), "s": str(soils[i]), "c": str(crops[i])} for i in range(n_samples)]
            fert_params = [{"t": float(temperatures[i]), "s": str(soils[i]), "pc": str(crops[i]), "f": str(fertilizers[i])} for i in range(n_samples)]

            conn.execute(text("DELETE FROM crop_training_data"))
            conn.execute(text("DELETE FROM fertilizer_training_data"))
            conn.commit()

            conn.execute(
                text("INSERT INTO crop_training_data (temperature, soil_type, crop) VALUES (:t, :s, :c)"),
                crop_params
            )
            conn.execute(
                text("INSERT INTO fertilizer_training_data (temperature, soil_type, predicted_crop, fertilizer) VALUES (:t, :s, :pc, :f)"),
                fert_params
            )
            conn.commit()
            print(f"  [OK] Seeded {n_samples} records into the database.")

        # Check and create document_templates
        try:
            conn.execute(text("SELECT 1 FROM document_templates WHERE ROWNUM = 1"))
        except Exception:
            print("  [INFO] Table 'document_templates' does not exist. Creating...")
            conn.execute(text("""
                CREATE TABLE document_templates (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    doc_type VARCHAR2(50),
                    category VARCHAR2(100),
                    section VARCHAR2(50),
                    template_text VARCHAR2(2000)
                )
            """))
            conn.commit()

        # Seed document_templates if empty
        template_count = conn.execute(text("SELECT COUNT(*) FROM document_templates")).scalar()
        if template_count == 0:
            print("  [INFO] Seeding document templates into Oracle DB...")
            templates = [
                # Poems
                ("POEM", "agriculture", "stanza1", "The golden seeds in fertile ground, / Under the sun, a life is found. / The farmer works from dawn to night, / To guide the green shoots to the light."),
                ("POEM", "agriculture", "stanza2", "With gentle rain and sweat of brow, / The harvest comes to greet us now. / A dance of soil, of wind, of grain, / A sweet reward for all the pain."),
                ("POEM", "technology", "stanza1", "In silent lines of code they sleep, / The promises the servers keep. / A digital world of shifting light, / That shines across the quiet night."),
                ("POEM", "technology", "stanza2", "From microchips to global webs, / The human tide that flows and ebbs. / We build the future, brick by byte, / A modern spark of thinking light."),
                ("POEM", "general", "stanza1", "The winding roads of time we tread, / With dreams of tomorrow ahead. / A silent hope that starts to grow, / In every heart that comes to know."),
                ("POEM", "general", "stanza2", "Through stormy skies and sunny days, / We find our path in different ways. / A simple truth to guide the soul, / To make the broken spirit whole."),
                
                # Articles
                ("ARTICLE", "agriculture", "title", "The Future of Farming: Sustainable Agriculture in the 21st Century"),
                ("ARTICLE", "agriculture", "intro", "Agriculture remains the backbone of human civilization. As our population grows, the need for sustainable farming practices has become more critical than ever."),
                ("ARTICLE", "agriculture", "body", "Modern agricultural techniques combine traditional knowledge with cutting-edge technology. Smart irrigation, organic soil enrichment, and integrated pest management are transforming how we grow our food, ensuring high yields while protecting our planet."),
                ("ARTICLE", "agriculture", "conclusion", "By supporting local farmers and embracing sustainable innovations, we can build a resilient food system that feeds the world without depleting our natural resources."),
                
                ("ARTICLE", "technology", "title", "Bridging the Digital Divide: How Tech Shapes Our World"),
                ("ARTICLE", "technology", "intro", "From artificial intelligence to edge computing, technology is evolving at an unprecedented pace, changing how we live, work, and communicate."),
                ("ARTICLE", "technology", "body", "The deployment of 5G networks, cloud infrastructures, and AI analytics has democratized information access. However, ensuring cybersecurity and digital literacy remains a significant challenge that requires global collaboration."),
                ("ARTICLE", "technology", "conclusion", "Technology is a powerful tool. When developed ethically and distributed equitably, it has the potential to solve some of humanity's greatest challenges."),

                # Essays
                ("ESSAY", "agriculture", "title", "The Socio-Economic Impact of Agricultural Modernization"),
                ("ESSAY", "agriculture", "intro", "Agriculture has transitioned from a labor-intensive survival mechanism into a technology-driven economic sector. This essay explores the socio-economic implications of this transition."),
                ("ESSAY", "agriculture", "body", "Modernization increases efficiency and yields, lifting many rural communities out of poverty. However, it also introduces challenges, such as the high cost of inputs and the potential displacement of traditional labor, necessitating balanced policy interventions."),
                ("ESSAY", "agriculture", "conclusion", "In conclusion, agricultural modernization is essential for food security, but it must be paired with education and economic safety nets to ensure inclusive growth."),
                
                ("ESSAY", "technology", "title", "Artificial Intelligence: The Catalyst for Future Innovation"),
                ("ESSAY", "technology", "intro", "Artificial Intelligence (AI) has emerged as the defining technology of the 21st century, sparking debate about its potential and risks."),
                ("ESSAY", "technology", "body", "AI models process massive datasets to automate tasks and detect complex patterns. While this increases productivity across healthcare, finance, and logistics, it also raises ethical concerns regarding data privacy and bias."),
                ("ESSAY", "technology", "conclusion", "In conclusion, AI is an amplifying force for human capability. Responsible development and regulatory oversight will be key to harnessing its potential."),

                # Applications
                ("APPLICATION", "leave", "title", "Application for Leave"),
                ("APPLICATION", "leave", "intro", "To,\nThe Principal / Manager,\n[Organization Name]"),
                ("APPLICATION", "leave", "subject", "Subject: Request for leave of absence"),
                ("APPLICATION", "leave", "body", "Dear Sir/Madam,\n\nI am writing to formally request leave starting from [Start Date] to [End Date] due to personal commitments. I have ensured that my immediate responsibilities are covered in my absence."),
                ("APPLICATION", "leave", "closing", "I will be reachable via email in case of urgent queries. Thank you for considering my request.\n\nSincerely,\n[Your Name]"),
                
                ("APPLICATION", "job", "title", "Application for Employment"),
                ("APPLICATION", "job", "intro", "To,\nThe Hiring Manager,\n[Company Name]"),
                ("APPLICATION", "job", "subject", "Subject: Application for [Job Position]"),
                ("APPLICATION", "job", "body", "Dear Hiring Team,\n\nI am writing to express my strong interest in the [Job Position] role. With my background and skillset, I am confident in my ability to make a meaningful contribution to your organization."),
                ("APPLICATION", "job", "closing", "Please find my attached resume for your consideration. I look forward to discussing my application in detail.\n\nSincerely,\n[Your Name]"),

                # Mails
                ("MAIL", "business", "subject", "Subject: Project Milestones and Next Steps"),
                ("MAIL", "business", "salutation", "Dear Team,"),
                ("MAIL", "business", "body", "I hope you are doing well. I wanted to share a quick update regarding our project progress. We have successfully completed our initial objectives and are preparing for the next phase starting next week."),
                ("MAIL", "business", "closing", "Please review the attached timeline and let me know if you have any feedback. Thank you for your dedication.\n\nBest regards,\n[Your Name]"),
                
                ("MAIL", "leave", "subject", "Subject: Out of Office: [Your Name]"),
                ("MAIL", "leave", "salutation", "Hi All,"),
                ("MAIL", "leave", "body", "Please note that I will be out of the office with limited access to my email. For urgent requests, please contact my backup at [Backup Contact]."),
                ("MAIL", "leave", "closing", "Thank you,\n[Your Name]")
            ]
            
            params = [{"t": row[0], "c": row[1], "s": row[2], "txt": row[3]} for row in templates]
            conn.execute(
                text("INSERT INTO document_templates (doc_type, category, section, template_text) VALUES (:t, :c, :s, :txt)"),
                params
            )
            conn.commit()
            print(f"  [OK] Seeded {len(templates)} templates into document_templates.")

def log_model_metadata(engine, model_name, count, accuracy):
    try:
        with engine.connect() as conn:
            conn.execute(
                text("INSERT INTO ml_model_metadata (model_name, records_count, accuracy, status) VALUES (:m, :c, :a, 'SUCCESS')"),
                {"m": model_name, "c": count, "a": float(accuracy)}
            )
            conn.commit()
            print(f"  [DB Log] Stored metadata for '{model_name}' in the database.")
    except Exception as db_err:
        print(f"  [WARN] Failed to log model metadata to database: {db_err}")

print("\n[1/5] Connecting to Oracle Database...")
try:
    engine = create_engine(db_url)
    with engine.connect() as conn:
        conn.execute(text("SELECT 1 FROM DUAL"))
    print("  [OK] Oracle DB connection successful.")

    # Ensure tables exist and are seeded
    ensure_tables_exist_and_seeded(engine)

    # Fetch Crop Training Data
    print("\n[2/5] Fetching training data from database...")
    crop_df = pd.read_sql(
        "SELECT temperature, soil_type, crop FROM crop_training_data",
        engine
    )
    print(f"  [OK] CROP_TRAINING_DATA: {len(crop_df)} records loaded.")

    # Fetch Fertilizer Training Data
    fert_df = pd.read_sql(
        "SELECT temperature, soil_type, predicted_crop, fertilizer FROM fertilizer_training_data",
        engine
    )
    print(f"  [OK] FERTILIZER_TRAINING_DATA: {len(fert_df)} records loaded.")

except Exception as e:
    print(f"  [FAIL] Database connection failed: {e}")
    sys.exit(1)


# ==========================================
# Train Crop Prediction Model
# ==========================================
print("\n[3/5] Training Crop Prediction Model (RandomForestClassifier)...")

# Fit Soil Type Encoder
ALL_SOILS = [
    "Alkaline", "Alluvial", "Black", "Brown", "Chalky", "Chernozem", "Clayey", "Desert",
    "Forest", "Gravelly", "Laterite", "Lateritic", "Loamy", "Marshy", "Mediterranean",
    "Mountain", "Peaty", "Permafrost", "Podzol", "Red", "Saline", "Sandy", "Silty",
    "Tundra", "Volcanic", "Yellow"
]
soil_encoder = LabelEncoder()
soil_encoder.fit(ALL_SOILS)
joblib.dump(soil_encoder, "assets/soil_encoder.pkl")
print("  [OK] Saved assets/soil_encoder.pkl")

def safe_encode_soil(soil_name):
    try:
        return soil_encoder.transform([soil_name])[0]
    except ValueError:
        return 0

crop_df["soil_encoded"] = crop_df["soil_type"].apply(safe_encode_soil)
X_crop = crop_df[["temperature", "soil_encoded"]].values
y_crop = crop_df["crop"].values

crop_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
crop_model.fit(X_crop, y_crop)

joblib.dump(crop_model, "assets/crop_model.pkl")
print("  [OK] Saved assets/crop_model.pkl")

# Calculate & log crop model training accuracy to DB
crop_acc = crop_model.score(X_crop, y_crop)
print(f"  [OK] Training Accuracy: {crop_acc:.4f}")
log_model_metadata(engine, "crop_model", len(crop_df), crop_acc)


# ==========================================
# Train Fertilizer Recommendation Model
# ==========================================
print("\n[4/5] Training Fertilizer Recommendation Model (RandomForestClassifier)...")

ALL_CROPS = [
    "Almond", "Apple", "Arecanut", "Avocado", "Bamboo", "Banana", "Barley", "Barnyard Millet",
    "Beetroot", "Bitter Gourd", "Blackgram", "Bottle Gourd", "Brinjal", "Broccoli", "Cabbage",
    "Capsicum", "Carrot", "Cashew", "Cauliflower", "Chickpea", "Chili", "Cocoa", "Coconut",
    "Coffee", "Coriander", "Cotton", "Cowpea", "Cucumber", "Custard Apple", "Dragon Fruit",
    "Fig", "Finger Millet", "Flax", "Foxtail Millet", "Garlic", "Ginger", "Grapes", "Green Gram",
    "Groundnut", "Guava", "Horse Gram", "Jackfruit", "Jute", "Kidneybeans", "Kodo Millet",
    "Lentil", "Little Millet", "Lychee", "Maize", "Mango", "Millet", "Mint", "Mungbean",
    "Muskmelon", "Mustard", "Oats", "Onion", "Orange", "Papaya", "Peas", "Pearl Millet",
    "Pigeonpeas", "Pineapple", "Pomegranate", "Potato", "Pumpkin", "Quinoa", "Radish", "Rice",
    "Rubber", "Rye", "Saffron", "Sapota", "Sesame", "Sorghum", "Soybean", "Spinach", "Strawberry",
    "Sugarcane", "Sunflower", "Sweet Potato", "Tapioca", "Tea", "Tea Leaves", "Tobacco",
    "Tomato", "Turmeric", "Walnut", "Watermelon", "Wheat"
]
crop_encoder = LabelEncoder()
crop_encoder.fit(ALL_CROPS)

def safe_encode_crop(crop_name):
    try:
        return crop_encoder.transform([crop_name])[0]
    except ValueError:
        return 0

fert_df_work = fert_df.copy()
fert_df_work["soil_encoded"] = fert_df_work["soil_type"].apply(safe_encode_soil)
fert_df_work["crop_encoded"] = fert_df_work["predicted_crop"].apply(safe_encode_crop)

X_fert = fert_df_work[["temperature", "soil_encoded", "crop_encoded"]].values
y_fert = fert_df_work["fertilizer"].values

fert_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
fert_model.fit(X_fert, y_fert)

joblib.dump(fert_model, "assets/fertilizer_model.pkl")
joblib.dump(crop_encoder, "assets/crop_encoder.pkl")
print("  [OK] Saved assets/fertilizer_model.pkl")
print("  [OK] Saved assets/crop_encoder.pkl")

# Calculate & log fertilizer model training accuracy to DB
fert_acc = fert_model.score(X_fert, y_fert)
print(f"  [OK] Training Accuracy: {fert_acc:.4f}")
log_model_metadata(engine, "fertilizer_model", len(fert_df), fert_acc)


# ==========================================
# Train India GK Retrieval Model
# ==========================================
print("\n[5/5] Training India GK Retrieval Model (TF-IDF)...")
try:
    from sklearn.feature_extraction.text import TfidfVectorizer
    print("  Fetching INDIA_GK_DATA from database...")
    gk_engine = create_engine(db_url)
    with gk_engine.connect() as conn:
        query = """
        SELECT question, answer FROM (
            SELECT question, answer, ROW_NUMBER() OVER (PARTITION BY category ORDER BY id DESC) as rn 
            FROM india_gk_data
        ) WHERE rn <= 200000
        """
        gk_df = pd.read_sql(query, conn)
    print(f"  [OK] INDIA_GK_DATA (Stratified): {len(gk_df)} records loaded for model training.")

    if len(gk_df) > 0:
        print("  Fitting TfidfVectorizer on representative sample...")
        gk_vectorizer = TfidfVectorizer(max_features=10000, stop_words='english')
        X_gk = gk_vectorizer.fit_transform(gk_df["question"])
        
        joblib.dump(gk_vectorizer, "assets/gk_vectorizer.pkl")
        joblib.dump(X_gk, "assets/gk_matrix.pkl")
        joblib.dump(gk_df["answer"].values, "assets/gk_answers.pkl")
        print("  [OK] Saved assets/gk_vectorizer.pkl")
        print("  [OK] Saved assets/gk_matrix.pkl")
        print("  [OK] Saved assets/gk_answers.pkl")
        
        # Log GK retrieval model to DB
        log_model_metadata(engine, "gk_retrieval_model", len(gk_df), 1.0)

        # ==========================================
        # Train Deep Learning Neural Network Model
        # ==========================================
        print("\n[6/5] Training Deep Learning Neural Network Model...")
        try:
            # Sample 5000 records for fast local CPU training
            gk_sub_df = gk_df.sample(n=min(5000, len(gk_df)), random_state=42).copy()
            
            nn_vectorizer = TfidfVectorizer(max_features=1000, stop_words='english')
            X_train_vec = nn_vectorizer.fit_transform(gk_sub_df["question"]).toarray()
            
            unique_answers = gk_sub_df["answer"].unique()
            ans_to_label = {ans: idx for idx, ans in enumerate(unique_answers)}
            gk_sub_df["label"] = gk_sub_df["answer"].map(ans_to_label)
            y_train = gk_sub_df["label"].values

            # Try PyTorch first, if not available, fall back to sklearn's MLPClassifier
            use_pytorch = False
            try:
                import torch
                import torch.nn as nn
                import torch.optim as optim
                use_pytorch = True
            except ImportError:
                print("  [INFO] PyTorch not installed. Using scikit-learn MLPClassifier (Neural Network) as a robust, lightweight fallback.")

            if use_pytorch:
                X_tensor = torch.tensor(X_train_vec, dtype=torch.float32)
                y_tensor = torch.tensor(y_train, dtype=torch.long)
                
                class GKNet(nn.Module):
                    def __init__(self, input_dim, hidden_dim, output_dim):
                        super(GKNet, self).__init__()
                        self.fc1 = nn.Linear(input_dim, hidden_dim)
                        self.relu = nn.ReLU()
                        self.fc2 = nn.Linear(hidden_dim, output_dim)
                    def forward(self, x):
                        return self.fc2(self.relu(self.fc1(x)))
                        
                input_dim = 1000
                hidden_dim = 128
                output_dim = len(unique_answers)
                
                nn_model = GKNet(input_dim, hidden_dim, output_dim)
                criterion = nn.CrossEntropyLoss()
                optimizer = optim.Adam(nn_model.parameters(), lr=0.01)
                
                nn_model.train()
                for epoch in range(15):
                    optimizer.zero_grad()
                    outputs = nn_model(X_tensor)
                    loss = criterion(outputs, y_tensor)
                    loss.backward()
                    optimizer.step()
                    
                nn_model.eval()
                with torch.no_grad():
                    outputs = nn_model(X_tensor)
                    _, predicted = torch.max(outputs, 1)
                    nn_acc = (predicted == y_tensor).sum().item() / len(y_tensor)
                    
                print(f"  [OK] PyTorch Neural Net Training Accuracy: {nn_acc:.4f}")
                torch.save(nn_model.state_dict(), "assets/gk_pytorch_model.pth")
                joblib.dump("pytorch", "assets/gk_nn_type.pkl")
            else:
                from sklearn.neural_network import MLPClassifier
                nn_model = MLPClassifier(hidden_layer_sizes=(128,), max_iter=20, alpha=1e-4,
                                         solver='adam', random_state=42, learning_rate_init=0.01)
                nn_model.fit(X_train_vec, y_train)
                nn_acc = nn_model.score(X_train_vec, y_train)
                print(f"  [OK] MLP Neural Net Training Accuracy: {nn_acc:.4f}")
                joblib.dump(nn_model, "assets/gk_mlp_model.pkl")
                joblib.dump("mlp", "assets/gk_nn_type.pkl")

            joblib.dump(nn_vectorizer, "assets/gk_vectorizer_nn.pkl")
            joblib.dump(unique_answers, "assets/gk_answers_nn.pkl")
            print("  [OK] Saved neural network model assets.")
            
            # Log training metadata to DB
            log_model_metadata(engine, "gk_neural_net", len(gk_sub_df), nn_acc)
        except Exception as nn_err:
            print(f"  [FAIL] Failed to train Neural Network GK model: {nn_err}")

    else:
        print("  [WARN] No GK records found. Skipping GK model training.")
except Exception as e:
    print(f"  [FAIL] Failed to train GK model: {e}")


# ==========================================
# [7/7] Train Mathematical Intelligence Model (100,000 Records)
# ==========================================
print("\n[7/7] Training Mathematical Intelligence Model (100,000 Records)...")
try:
    from train_math_model import ensure_math_table, seed_math_data_if_needed, train_mathematical_model
    ensure_math_table(engine)
    seed_math_data_if_needed(engine, target_count=100000, force=False)
    math_acc, math_meta = train_mathematical_model(engine, total_records=100000)
    print(f"  [OK] Mathematical Intelligence Model Accuracy: {math_acc:.4f} across 100,000 records.")
except Exception as math_err:
    print(f"  [FAIL] Failed to train Mathematical model: {math_err}")


print("\n" + "=" * 60)
print("  Training completed successfully!")
print(f"  Soil classes:       {list(soil_encoder.classes_)}")
print(f"  Crop classes:       {list(crop_encoder.classes_)}")
print(f"  Crop records:       {len(crop_df)}")
print(f"  Fertilizer records: {len(fert_df)}")
if 'gk_df' in locals() or 'gk_df' in globals():
    print(f"  India GK records:   {len(gk_df)}")
if 'math_meta' in locals() or 'math_meta' in globals():
    print(f"  Math records:       {math_meta.get('records_count', 100000)}")
print("=" * 60)
