spring.application.name=demo
server.port=${PORT:9090}

# Database properties
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/omegadb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
