-- =============================================================================
-- OMEGA DATABASE SCHEMA SPECIFICATION
-- Database Platform: Oracle Database 19c / 21c Enterprise / Express Edition
-- Schema: OMEGA_user
-- Total Tables: 13 | Records: 33,177,035+ | Domain Categories: 4
-- =============================================================================

-- =============================================================================
-- DOMAIN 1: WORKSPACE & OPERATIONAL TABLES
-- =============================================================================

-- 1.1 Chat Sessions
CREATE TABLE chat_sessions (
    id VARCHAR2(255) PRIMARY KEY,
    title VARCHAR2(1000),
    created_at NUMBER(20),
    updated_at NUMBER(20)
);

-- 1.2 Chat Messages (Child of Chat Sessions)
CREATE TABLE chat_messages (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id VARCHAR2(255) NOT NULL,
    sender VARCHAR2(50),
    content CLOB,
    timestamp VARCHAR2(50),
    created_at NUMBER(20),
    CONSTRAINT fk_chat_msg_session FOREIGN KEY (session_id) 
        REFERENCES chat_sessions(id) ON DELETE CASCADE
);
CREATE INDEX idx_chat_msg_session_time ON chat_messages(session_id, created_at);

-- 1.3 Document Templates
CREATE TABLE document_templates (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_type VARCHAR2(50),
    category VARCHAR2(100),
    section VARCHAR2(50),
    template_text VARCHAR2(2000)
);
CREATE INDEX idx_doc_type_cat ON document_templates(doc_type, category);

-- =============================================================================
-- DOMAIN 2: KNOWLEDGE BASE DOMAIN
-- =============================================================================

-- 2.1 India General Knowledge (12 Million Records)
CREATE TABLE india_gk_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(255),
    question CLOB,
    answer CLOB,
    difficulty VARCHAR2(50)
);
-- Text Index: CREATE INDEX idx_gk_question ON india_gk_data(question) INDEXTYPE IS CTXSYS.CONTEXT;

-- 2.2 Agricultural Knowledge Base (200,000 Records)
CREATE TABLE agri_knowledge_base (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR2(255),
    topic VARCHAR2(255),
    keywords VARCHAR2(1000),
    content CLOB
);
CREATE INDEX idx_agri_domain_topic ON agri_knowledge_base(domain, topic);

-- 2.3 Mathematical Intelligence Knowledge (100,000 Records)
CREATE TABLE math_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR2(1000),
    formula VARCHAR2(500),
    solution VARCHAR2(2000),
    topic VARCHAR2(100),
    difficulty VARCHAR2(50)
);
CREATE INDEX idx_math_topic_diff ON math_training_data(topic, difficulty);

-- =============================================================================
-- DOMAIN 3: MACHINE LEARNING TRAINING DATA DOMAIN
-- =============================================================================

-- 3.1 Conversation Training Data (300,000 Records)
CREATE TABLE conversation_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR2(255),
    difficulty VARCHAR2(50),
    instruction CLOB,
    response CLOB
);
CREATE INDEX idx_conv_cat_diff ON conversation_training_data(category, difficulty);

-- 3.2 Dialog Multi-Turn Training Data (112,635 Records)
CREATE TABLE dialog_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dialog_id VARCHAR2(255),
    turn_number NUMBER(10),
    role VARCHAR2(50),
    message CLOB
);
CREATE INDEX idx_dialog_id_turn ON dialog_training_data(dialog_id, turn_number);

-- 3.3 Natural Language Intent Training Data (200,000 Records)
CREATE TABLE intent_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utterance VARCHAR2(1000),
    intent VARCHAR2(255),
    entities VARCHAR2(1000)
);
CREATE INDEX idx_intent_intent ON intent_training_data(intent);

-- 3.4 AI Response Feedback & RLHF Data (200,000 Records)
CREATE TABLE feedback_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_query VARCHAR2(1000),
    ai_response CLOB,
    rating NUMBER(5),
    sentiment VARCHAR2(50)
);
CREATE INDEX idx_feedback_rating_sent ON feedback_training_data(rating, sentiment);

-- 3.5 Crop Recommendation ML Training Data (2,000 Records)
CREATE TABLE crop_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature NUMBER(10,2),
    soil_type VARCHAR2(100),
    crop VARCHAR2(100)
);
CREATE INDEX idx_crop_soil_crop ON crop_training_data(soil_type, crop);

-- 3.6 Fertilizer Recommendation ML Training Data (2,000 Records)
CREATE TABLE fertilizer_training_data (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    temperature NUMBER(10,2),
    soil_type VARCHAR2(100),
    predicted_crop VARCHAR2(100),
    fertilizer VARCHAR2(100)
);
CREATE INDEX idx_fert_soil_crop ON fertilizer_training_data(soil_type, predicted_crop);

-- =============================================================================
-- DOMAIN 4: MLOPS & MODEL METADATA
-- =============================================================================

-- 4.1 ML Model Metadata
CREATE TABLE ml_model_metadata (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR2(100),
    training_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    records_count NUMBER(15),
    accuracy NUMBER(10,4),
    status VARCHAR2(50)
);
CREATE INDEX idx_ml_meta_model_time ON ml_model_metadata(model_name, training_time);

-- =============================================================================
-- LOGICAL VIEWS
-- =============================================================================

-- View 1: Master Database Catalog
CREATE OR REPLACE VIEW v_database_catalog AS
SELECT 
    t.table_name,
    CASE 
        WHEN t.table_name IN ('INDIA_GK_DATA', 'AGRI_KNOWLEDGE_BASE', 'MATH_TRAINING_DATA') THEN 'KNOWLEDGE_BASE'
        WHEN t.table_name IN ('CONVERSATION_TRAINING_DATA', 'DIALOG_TRAINING_DATA', 'INTENT_TRAINING_DATA', 'FEEDBACK_TRAINING_DATA', 'CROP_TRAINING_DATA', 'FERTILIZER_TRAINING_DATA') THEN 'TRAINING_DATA'
        WHEN t.table_name IN ('CHAT_SESSIONS', 'CHAT_MESSAGES', 'DOCUMENT_TEMPLATES') THEN 'WORKSPACE_OPS'
        WHEN t.table_name IN ('ML_MODEL_METADATA') THEN 'MLOPS_METADATA'
        ELSE 'SYSTEM'
    END AS domain_category,
    s.bytes / (1024 * 1024) AS storage_mb
FROM user_tables t
LEFT JOIN (
    SELECT segment_name, SUM(bytes) AS bytes
    FROM user_segments
    GROUP BY segment_name
) s ON t.table_name = s.segment_name
WHERE t.table_name NOT LIKE 'DR$%';

-- View 2: Chat Sessions Summary
CREATE OR REPLACE VIEW v_chat_session_summary AS
SELECT 
    s.id AS session_id,
    s.title,
    s.created_at,
    s.updated_at,
    COUNT(m.id) AS total_messages,
    SUM(CASE WHEN m.sender = 'user' THEN 1 ELSE 0 END) AS user_messages,
    SUM(CASE WHEN m.sender = 'assistant' THEN 1 ELSE 0 END) AS assistant_messages,
    MAX(m.created_at) AS last_message_at
FROM chat_sessions s
LEFT JOIN chat_messages m ON s.id = m.session_id
GROUP BY s.id, s.title, s.created_at, s.updated_at;

-- View 3: Latest ML Model Leaderboard
CREATE OR REPLACE VIEW v_model_leaderboard AS
SELECT 
    m.model_name,
    m.records_count,
    m.accuracy,
    m.status,
    m.training_time
FROM ml_model_metadata m
WHERE m.id IN (
    SELECT MAX(id) FROM ml_model_metadata GROUP BY model_name
);
